name: CI/CD Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Хуярим код из репы
        uses: actions/checkout@v3

      - name: Ставим ноду
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Ставим зависимости
        run: npm ci

      - name: Проверяем линтером
        run: npm run lint

      - name: Собираем
        run: npm run build

      - name: Деплоим на сервер
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            rm -rf /app/temp
            mkdir -p /app/temp
            cd /app/temp
            git clone https://github.com/${{ github.repository }}.git .
            npm ci
            npm run build
            cp -r build/* /app/
            cp docker-compose.yml /app/
            cp nginx.conf /app/
            cd /app
            docker-compose up -d --build
            rm -rf /app/temp