name: CI/CD Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Хуярим код из репы
        uses: actions/checkout@v3

      - name: Ставим ноду
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Ставим зависимости
        run: npm ci

      - name: Проверяем линтером
        run: npm run lint

      - name: Собираем
        run: npm run build

      - name: Деплоим на сервер
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /app
            git pull
            docker build -t frontend-build .
            docker run --name frontend-build-container frontend-build
            rm -R static
            docker cp frontend-build-container:/static ./static
            docker rm frontend-build-container
